### ISSUE TITLE
Size Audio player HTML5 gib

### ISSUE THREAD

**Issue by EMartinezM** [momo10216/html5video#1]
I nice to change the size of the Video Player, but in audio i can´t control the size. I could be better than the size it was automatic whatever the resoluction was (smatphone, Ipad,....) But i can see that in my smartphone , the audio player it goes out the margin of the page.

**Comment by momo10216** [comment]
I will take care about this issue. Thanks for reporting.

**Comment by momo10216** [comment]
Fixed
