### ISSUE TITLE
Video and audio link relative to joomla website.

### ISSUE THREAD

**Issue by ElephantInTheRoomFirst** [momo10216/html5video#5]
Now the path of audio and video file has to be absolute path. 
```
Example audio: {html5audio controls=[1] autoplay=[0] preload=[auto] loop=[0] audio_mp3=[http://cczwei.mirror.speedpartner.de/cc2audio/CC-Zwei-380.mp3] audio_ogg=[http://cczwei.mirror.speedpartner.de/cc2audio/CC-Zwei-380.ogg]}

Example video: {html5video width=[640] height=[360] controls=[1] autoplay=[0] preload=[auto] poster_visibility=[1] loop=[0] video_mp4=[http://media.w3.org/2010/05/sintel/trailer.mp4] video_ogg=[http://media.w3.org/2010/05/sintel/trailer.ogv] poster=[http://media.w3.org/2010/05/sintel/poster.png]}
```

Can it be made relative to joomla media folder? The file path can be either absolute or relaive. It is relative then add joomla base url before the path to make it absolute. 
```
{html5audio audio_mp3=[images/audio/MonaLisa-Why-so-Famous.mp3] }
{html5video video_mp4=[images/video/MonaLisa-Why-so-Famous480x360.mp4] }
```

**Comment by ElephantInTheRoomFirst** [comment]
It works. Something was wrong on my side.

**Comment by Bacchushlg** [comment]
I try to play an audio file that is placed under "images/...", similar to what is written above:
{html5audio audio_mp3=[images/audio/MonaLisa-Why-so-Famous.mp3] }
But I don't get it running.
Under Firefox and Opera I get "your browser does not support HTML5 when I view the page in the Inspector. But they support HTML5, don't they
