### ISSUE TITLE
What about responsive websites?

### ISSUE THREAD

**Issue by Entangled8qubit** [momo10216/html5video#6]
Hi,

I am trying to use this great extension on a responsive Joomla website.
Is there any way to change the video player's dimensions when the browser window is resized?

Thank you in advance.

**Comment by momo10216** [comment]
Add class & id to params
Add link to wiki https://www.w3schools.com/Css/css_rwd_videos.asp

**Comment by Entangled8qubit** [comment]
Hi momo10216,

Thank you so much for your reply.
I found out that if your set width and height to 100%, in the parameters, it works great with any resolution.
`i.e: {html5video controls=[0] width=[100%] height=[100%] autoplay=[1] preload=[auto] poster_visibility=[0] loop=[1] video_mp4=[http://www.video.com/video.mp4]}`
Regards :)

**Comment by momo10216** [comment]
Checked class & id were already set for identification. Extended the wiki about this.
